export const dictionary = {
  en: {
    committee: "Our Committee",
    career: "Career",
    headoffice: "Central Office , Koteshwor , Kathmandu",
    feedback: "Feedback",
    tos: "Terms and Condition",
    company: "Company",
    companyname: "KAUDINYA GOTRIYA",
    cooperativeLtd: "MAHASAMAJ",
    usefulLinks: "Useful Links",
    services: "Services",
    phone: "023-590087",
    millionaire: "Millionaire Savings Plan",
    homeWelcomContent: "",
    contactContent: "",
  },
  np: {
    committee: "संचालक समिति ",
    career: "क्यारियर",
    headoffice: "केन्द्रीय कार्यालय , कोटेश्वर , काठमाडौं",
    feedback: "प्रतिक्रिया",
    tos: "नियम र शर्त",
    company: "कम्पनी",
    satlok: "सतलोक",
    companyname: "कौण्डिन्य गोत्रिया ",
    multipurpose: "महासमाज",
    satlokMultipurpose: "सतलोक  बहुउद्देश्यीय",
    cooperativeLtd: "महासमाज",
    usefulLinks: "उपयोगी लिङ्कहरू",
    services: "हाम्रा सेवाहरु",
    phone: "०२३-५९००८७",
    millionaire: "लखपती बचत",
    homeWelcomContent: "",
    contactContent: "",
  },
};
